language: java

sudo: required

services:
  - docker
  
jdk:
  - oraclejdk8
  - openjdk8

script:
   - ./gradlew check buildDocker

# After success will push to Docker Hub
after_success:
  - set
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi
