language: java

sudo: required

services:
  - docker
  
jdk:
  - openjdk8

script:
   - ./gradlew check buildDocker

# After success will push image to Docker Hub
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker images;
    docker push eyallupu/aad-sample-webapp:latest;
    fi
